/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QuestionBuilder.java
 *
 * Created on Jun 29, 2010, 5:15:35 PM
 */

package my;

import my.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import javax.swing.JFileChooser;


/**
 *
 * @author MAHBUB
 */
public class QuestionBuilder extends javax.swing.JFrame {

    private String targetFolder;
    private String fileName;

    /** Creates new form QuestionBuilder */
    public QuestionBuilder() {
        super("Question Builder v1.0");
        initComponents();
    }

    private int Answer()
    {
        if(op1JCheckBox.isSelected())
            return 1;
        else if(op2JCheckBox.isSelected())
            return 2;
        else if(op3JCheckBox.isSelected())
            return 3;
        else if(op4JCheckBox.isSelected())
            return 4;
        else return 0;
    }

    private Question makeQuestion()
    {
        Question ques = new Question( questionTitleJTextArea.getText(), op1JTextField.getText(),
                                      op2JTextField.getText(), op3JTextField.getText(), op4JTextField.getText(),
                                      Answer());
        return ques;
    }

    private void buildQuestion()
    {
        targetFolder = targetFolderJTextField.getText();
        fileName = fileNameJTextField.getText();

        try {
//            ObjectOutputStream objectOutput = new ObjectOutputStream( new FileOutputStream("E:\\Documents and Settings\\" +
//                                                                    "MAHBUB\\My Documents\\WhoWantsToBeAMillioner\\" +
//                                                                    "QuestionDatabase\\ques1.txt"));

            ObjectOutputStream objectOutput = new ObjectOutputStream( new FileOutputStream(targetFolder + "\\"+ fileName + ".ques"));

            objectOutput.writeObject(makeQuestion());
            objectOutput.flush();
            objectOutput.close();

        }
        catch (IOException ioException) {
            System.out.println("IOException occurred");
            setStatus("I/O Exception Occured");
        }
    }


    private void setStatus(String msg)
    {
        statusJLabel.setText("Status : " + msg);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionTitleJTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        op1JTextField = new javax.swing.JTextField();
        op2JTextField = new javax.swing.JTextField();
        op3JTextField = new javax.swing.JTextField();
        op4JTextField = new javax.swing.JTextField();
        op1JCheckBox = new javax.swing.JCheckBox();
        op2JCheckBox = new javax.swing.JCheckBox();
        op3JCheckBox = new javax.swing.JCheckBox();
        op4JCheckBox = new javax.swing.JCheckBox();
        buildQuestionJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        targetFolderJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fileNameJTextField = new javax.swing.JTextField();
        fileBrowserJButton = new javax.swing.JButton();
        statusJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Question Title :");

        questionTitleJTextArea.setColumns(20);
        questionTitleJTextArea.setFont(new java.awt.Font("Calibri", 0, 14));
        questionTitleJTextArea.setRows(3);
        jScrollPane1.setViewportView(questionTitleJTextArea);

        jLabel2.setText("Options :");

        op1JCheckBox.setText("Answer");

        op2JCheckBox.setText("Answer");

        op3JCheckBox.setText("Answer");

        op4JCheckBox.setText("Answer");

        buildQuestionJButton.setFont(new java.awt.Font("Calibri", 1, 18));
        buildQuestionJButton.setText("Build Question");
        buildQuestionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildQuestionJButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Target Folder :");

        jLabel4.setText("File Name :");

        fileNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameJTextFieldActionPerformed(evt);
            }
        });

        fileBrowserJButton.setText("Browse");
        fileBrowserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileBrowserJButtonActionPerformed(evt);
            }
        });

        statusJLabel.setFont(new java.awt.Font("Calibri", 1, 18));
        statusJLabel.setForeground(new java.awt.Color(0, 153, 0));
        statusJLabel.setText("Status :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(op4JTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(op3JTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(op2JTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(op1JTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(op4JCheckBox)
                                    .addComponent(op3JCheckBox)
                                    .addComponent(op2JCheckBox)
                                    .addComponent(op1JCheckBox)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(targetFolderJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fileBrowserJButton))
                            .addComponent(fileNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(statusJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(buildQuestionJButton)
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(op1JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op1JCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op2JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op2JCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op3JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op3JCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op4JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op4JCheckBox))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(targetFolderJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileBrowserJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fileNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buildQuestionJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buildQuestionJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildQuestionJButtonActionPerformed
        buildQuestion();
        setStatus("Question successfully Built.");
    }//GEN-LAST:event_buildQuestionJButtonActionPerformed

    private void fileBrowserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileBrowserJButtonActionPerformed
        JFileChooser fileChooser;
        fileChooser = new JFileChooser();

        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fileChooser.showOpenDialog(this);

        File file = fileChooser.getSelectedFile();
        targetFolderJTextField.setText(file.getPath());
    }//GEN-LAST:event_fileBrowserJButtonActionPerformed

    private void fileNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameJTextFieldActionPerformed
        buildQuestion();
        setStatus("Question successfully Built.");
    }//GEN-LAST:event_fileNameJTextFieldActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionBuilder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buildQuestionJButton;
    private javax.swing.JButton fileBrowserJButton;
    private javax.swing.JTextField fileNameJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox op1JCheckBox;
    private javax.swing.JTextField op1JTextField;
    private javax.swing.JCheckBox op2JCheckBox;
    private javax.swing.JTextField op2JTextField;
    private javax.swing.JCheckBox op3JCheckBox;
    private javax.swing.JTextField op3JTextField;
    private javax.swing.JCheckBox op4JCheckBox;
    private javax.swing.JTextField op4JTextField;
    private javax.swing.JTextArea questionTitleJTextArea;
    private javax.swing.JLabel statusJLabel;
    private javax.swing.JTextField targetFolderJTextField;
    // End of variables declaration//GEN-END:variables

}
